version: '3'
services:
  bybit-order-alert:
    image: haynesx10/bybit-order-alert:${TAG}
    container_name: bybit-order-alert
    command: >
      sh -c "
      python -u main.py"
    ports:
      - 8000:8000
    expose:
      - 8000
    env_file:
      - ../env/bybit-order-alert.env

